const request = require("supertest");
const app = require("../../server/server.js");
const mongoose = require("mongoose");
afterAll(async () => {
  await mongoose.connection.close();
});

describe("Creating an account and manipulating the values", () => {
    let accessToken;
    let refreshToken;
    it("Create a new account", async () => {
        const res = await request(app).post("/account/create").send({
            email: "test5@gmu.edu",
            password: "123",
            type: "User",
        });

        // check for id that can only be generated by the mongo server
        expect(res.body).toHaveProperty("accountId");

        const cookies = res.headers['set-cookie'];
        const accessTokenCookie = cookies.find((cookie) => cookie.startsWith('access_token='));
        const refreshTokenCookie = cookies.find((cookie) => cookie.startsWith('refresh_token='));
        expect(accessTokenCookie).toBeDefined();
        expect(refreshTokenCookie).toBeDefined();
        accessToken = accessTokenCookie;
        refreshToken = refreshTokenCookie;
    });

    it("Update password", async() => {
        const res = await request(app)
            .put("/account/update")
            .set("Cookie", accessToken, refreshToken)
            .send({
            type: "Admin",
            password: "Stronger@pass123",
        });
        expect(res.statusCode).toBe(200);
        expect(res.body).toHaveProperty("type", "Admin")
    })

    it("Logout", async() => {
        const res = await request(app)
            .post("/account/logout")
            .set("Cookie", accessToken, refreshToken)

        expect(res.statusCode).toBe(200);

        expect(res.headers['set-cookie'][0]).toContain('Expires=Thu, 01 Jan 1970 00:00:00 GMT');
        expect(res.headers['set-cookie'][1]).toContain('Expires=Thu, 01 Jan 1970 00:00:00 GMT');
    })

    it("Login with new password", async() => {
        const res = await request(app).post("/account/login").send({
            email: "test5@gmu.edu",
            password: "Stronger@pass123"
        })

        expect(res.statusCode).toBe(200);

        const cookies = res.headers['set-cookie'];
        const accessTokenCookie = cookies.find((cookie) => cookie.startsWith('access_token='));
        const refreshTokenCookie = cookies.find((cookie) => cookie.startsWith('refresh_token='));
        expect(accessTokenCookie).toBeDefined();
        expect(refreshTokenCookie).toBeDefined();
    })

    it("Delete account", async() => {
        const res = await request(app).delete("/account/delete")
            .set("Cookie", accessToken, refreshToken)
        expect(res.statusCode).toBe(200);
    })
});

describe("Testing jwt authorization", () => {
    it("Create a new account", async () => {
        const res = await request(app).post("/account/create").send({
            email: "test8@gmu.edu",
            password: "123",
            type: "User",
        });

        // check for id that can only be generated by the mongo server
        expect(res.body).toHaveProperty("accountId");

        const cookies = res.headers['set-cookie'];
        const accessTokenCookie = cookies.find((cookie) => cookie.startsWith('access_token='));
        const refreshTokenCookie = cookies.find((cookie) => cookie.startsWith('refresh_token='));
        expect(accessTokenCookie).toBeDefined();
        expect(refreshTokenCookie).toBeDefined();
    });

    it("Update password", async() => {
        const res = await request(app)
            .put("/account/update")
            .send({
            type: "Admin",
            password: "Stronger@pass123",
        });

        expect(res.statusCode).toBe(403);
    })

    it("Logout", async() => {
        const res = await request(app)
            .post("/account/logout")

        expect(res.statusCode).toBe(403);
    })

    it("Login with new password", async() => {
        const res = await request(app).post("/account/login").send({
            email: "test8@gmu.edu",
            password: "Stronger@pass123"
        })

        expect(res.statusCode).toBe(401); //401 since password was never updated
    })

    it("Delete account", async() => {
        const res = await request(app).delete("/account/delete")
        expect(res.statusCode).toBe(403);
    })
})