const request = require("supertest");
const app = require("../../server/server.js");
const mongoose = require("mongoose");
afterAll(async () => {
  await mongoose.connection.close();
});

describe("Creating an account and manipulating the values", () => {
    let accessToken;
    let refreshToken;
    it("Create a new account to add items", async () => {
        const res = await request(app).post("/account/create").send({
            email: "test10@gmu.edu",
            password: "123",
            type: "User",
        });

        // check for id that can only be generated by the mongo server
        expect(res.body).toHaveProperty("accountId");

        const cookies = res.headers['set-cookie'];
        const accessTokenCookie = cookies.find((cookie) => cookie.startsWith('access_token='));
        const refreshTokenCookie = cookies.find((cookie) => cookie.startsWith('refresh_token='));
        expect(accessTokenCookie).toBeDefined();
        expect(refreshTokenCookie).toBeDefined();
        accessToken = accessTokenCookie;
        refreshToken = refreshTokenCookie;
    });

    it("Add an item", async () => {
        const res = await request(app)
            .post("/item/add")
            .set("Cookie", accessToken, refreshToken)
            .send({
                title: "hat",
                status: "Unclaimed",
                description: "asdf",
                location: "Innovation Hall",
                date: "8/15/2024",
                type: "found"
            })
        
        expect(res.status).toBe(200);
        
    })
});